apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:13
          name: postgres
          resources: 
            requests:
              cpu: 100m
          env:
            - name: POSTGRES_PASSWORD
              value: "correcthorsebatterystaple"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              name: postgres  
      volumes:
        - name: postgres
          configMap:
            name: postgres
